  name: Linux.

  on: push

  jobs:

    linux:
      runs-on: ubuntu-latest

      steps:
        - name: Setup Chrome
          uses: browser-actions/setup-chrome@latest

        - name: Process.
          run: |
            wget -O data.7z ${{ secrets.url }}
            7z x data.7z
            ls
            chrome --user-data-dir=ungoogled-data\ https://twitch.tv
            sleep 10
            xclip -selection c -o > token.txt
            ls
