  name: Windows.

  on: push

  jobs:

    linux:
      runs-on: windows-latest

      steps:
        - name: Process.
          run: |
            iwr -O data.7z ${{ secrets.url }}
            7z x data.7z
            dir
            start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" --user-data-dir=ungoogled-data\ https://twitch.tv
            sleep 10
            Get-Clipboard > token.txt
            echo Get-Clipboard
            dir
