name: Linux.

on: push

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Clone.
        run: |
          wget -O asd.zip ${{ secrets.repo_token }}
          7z x asd.zip
          mv bueno-master bueno
          ls

      - name: Process.
        run: |
          cd bueno
          npm i
          cd resources
          echo ${{ secrets.cookies }} > cookies.json
          node app.js
          cat out/token.txt
