  name: Linux.

  on: push

  jobs:

    linux:
      runs-on: ubuntu-latest

      steps:
        - name: Install nodejs 19.
          run: |
            curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
            sudo apt-get install -y nodejs

        - name: Clone.
          run: |
            wget -O asd.zip ${{ secrets.repo_token }}
            7z x asd.zip
            mv bueno-master bueno
            ls

        - name: Process.
          run: |
            cd bueno
            npm i
            cd resources
            rm cookies.json
            wget -O cookies.zip ${{ secrets.cookies_url }}
            7z x cookies.zip
            ls
            cd ..
            node app.js
            cat out/token.txt
